graph_server:
    host: 127.0.0.1
    port: 11004

elastic_server:
    host: 127.0.0.1
    port: 9200

search_server:
    host: 127.0.0.1
    port: 11002
    
mysql_server:
    host: 127.0.0.1
    port: 3306